<?php foreach ($this->data as $key => $value): ?>
    <ul class="zdt-toolbar-info-ul zdt-list <?php if ($this->isChild): ?> zdt-list-collapsible<?php endif; ?>">
    <?php if ($value instanceof \stdClass || is_array($value) || $value instanceof \Traversable): ?>
        <li>
            <a href="#" class="zdt-list-collapser"><?php echo $key; ?></a>
            <?php echo $this->partial('zend-developer-tools/request/data-part', array('data' => $value, 'isChild' => true)); ?>
        </li>
    <?php else: ?>
        <li>
            <?php if (!is_int($key)): ?>
                <?php echo $key; ?>:
            <?php endif; ?>
            <?php echo $value ?>
        </li>
    <?php endif; ?>
    </ul>
<?php endforeach; ?>