<!-- Note: Every \n will be stripped out. Inline CSS for now. -->

<?php
    $time   = sprintf('%.3f Seconds', $this->report->getCollector('time')->getExecutionTime());
    $memory = sprintf('%.2f Mb', $this->report->getCollector('memory')->getMemory() / 1024 / 1024);
?>

<div style="
width:100%;
height: 40px;
font: normal 13px/40px 'Helvetica Neue', Helvetica, Arial, sans-serif;
color: #eee;
position: fixed;
bottom: 0;
left: 0;
background: #2C2C2C;
background: -moz-linear-gradient(top,#333,#222);
background: -ms-linear-gradient(top,#333,#222);
background: -webkit-gradient(linear, 0 0, 0 100%, from(#333), to(#222));
background: -webkit-linear-gradient(top, 333, #222);
background: -o-linear-gradient(top, #333, #222);
background: linear-gradient(top, #333, #222);
-webkit-box-shadow: 0 -3px 3px rgba(0, 0, 0, 0.25);
-moz-box-shadow: 0 -3px 3px rgba(0, 0, 0, 0.25);
box-shadow: 0 -3px 3px rgba(0, 0, 0, 0.2);
">
<div style="
padding: 0 10px;
">
<img src="
data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAPCAYAAAAceBSiAA
AAAXNSR0IArs4c6QAAAAZiS0dEAH8A9wAAMkqpNAAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB
9wCCwIWGuaXOlYAAAJiSURBVDjLldS/i1xVFAfwz8leJxF/FdFUNjayhYpCkBATxEIwb0D/ADFpIjMg
CDGQQtBCIWVAY/EmIGKbRpt9q6CFplIL8UfvL2SLqBBRUHzDsdi3O7Ozb7KbA493udz7Pff7Pd9zYty
UkumrCI/YfxzARvJgcDeeT54Mbs/cP0iBCNEB7i/SNMNxPIBPcCRu4eURMwaS2DNd908Ir0yq9sfgTR
xZBN7jyw7xh4KpdA73LGaL8Lf0MoZia8tnddW+PVorgWdvQa0tipFsYHhTxqO18miEr3N29Y9J1R6Gc
VMCr+PfbfhZgl1Kd/9ppm8nw/ZjbiL3aK0U4TtptZMqUNVVu754drxWHhKOZjoYsYvwivTBZNhu9Bpu
SVzGagcWeK8v8agpDU7NG6nHYNdsSt0rxyLr0xHen6vUF3XVHtvFuClv4LUdFd0dv9ZVe/+4KSdxEY/
hF5wvPYnvjXAps2OS/slwtudcZHphrlX7uyM9060v4Wi3XsWV0iPFhzgcIaXo2ur7Jb16Q/qyx9it9D
MuT4bbd1/FIfyEb7ASC2zeifBSpuzYvFtX7dmlpmzKwKZC/9VVm/NmjTCd35sr1Sk0OBdzQI8H13Bbp
ojwZ2ek6zmTcUud63XV3uic/pRwAceSg8Gh5L5J1f7ek/g41nG1rtoXS5d4Jfg0GUSHntwhNRELTtp8
yQVcGTflOVyVBjk79NuSxA/jI3yOEZRuUq3jztgebGBF7Jx6He2MNOgecl4YzE0/OLOkSm/hLgwxHTf
FgeB08PQe7bLTxrHpdpzoBn5E+gtn6qptllx9YnHjf9NI2tXkjbmCAAAAAElFTkSuQmCC" alt="Zend Framework Logo" style="
padding: 13px 5px 0 0;
float: left;
">
<span style="margin: 0 20px 0 0; font-weight: bold;">Developer Toolbar</span>
<span>Time: <?php echo $time; ?>, Memory: <?php echo $memory; ?> – early demo ;o</span>
</div>
</div>