<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wHAw8kLbbW/+QAAAHwSURBVDjLnVTPq1JBFD7nznivgbcoJQliMnGZK0HbRNhKgsCdC2lh7dy58A/I/gHBv+QhBO8tXnvJlbUIxHIEKXKjoGnjzLR518Z7Nd+732p+fnO+850zCAZms9lTIcQFALhwGgoR3yWTyfeIqL1FBADgnCNjTDcajY9CCAYA4hqESCldt9vtZ5zzBWPsH+EV6ZfFYvFYKUXgmkBE7bouSaVSEW+N7uJXKhGLxW4Zh8GyrACJ1hqUUtoMxoRJuLcxnU7/dDqd74SQPfmFQuFhuVy+I6U8HLU3GA6HPwHgvjeXUl4ul8uhbdtvtN7lXK5Wq1fxePzCJMlkMhggHI1GvwAgASGQTqcxILlerw8A4F4IvtsHJQ8Ggx+m5BsAs9lsMMIrcjRdjkQiYORvZ56U8rTLftcmk8mm1Wp9tSxLmI8Ui8VH1Wo1sd1u/+9yv9/fcxkRLwkh35RSb43zkhDyUghxbpLkcrmgZEqpv0NeAIC/uInW+pxSejShu51KpfIJAO6GMMU9KLnX64Wuw3w+H5S82WyUr/HBtu3AZSklCCE0It6sl8fj8e9ms/mZUrpnZ6lUStVqtQfHevlo2TDGet1ulwshXpufTTQaLc/n87OTpjiO47fuuRCBfxbX6/WZ4zjH28aI6ENYlznnT7zJX1iYwsqME23RAAAAAElFTkSuQmCCSUVORK5CYII=" alt="Memory Peak">
        <span class="zdt-toolbar-info">
            <?php printf('%.2f Mb', $this->report->getCollector('memory')->getMemory() / 1024 / 1024); ?>
        </span>
    </div>
    <?php if ($this->collector->hasEventMemory()) : ?>
    <div class="zdt-toolbar-detail">
        <?php
        // todo: proper styling.
        foreach ($this->collector->getApplicationEventMemory() as $key => $value) {
            printf('<span class="zdt-toolbar-info"><strong style="width: 100px;float: left;">%s</strong>', $key);
            printf('<span style="width: 60px;float: right;text-align:right;">+%.0f Kb</span></span>', $value / 1024);
        }
        ?>
    </div>
    <?php endif; ?>
</div>