<!-- START Zend Developer Toolbar Style -->
<style type="text/css" media="screen">
<?php include __DIR__ . '/toolbar.css'; ?>

<?php if ($this->position === 'top') : ?>
#zend-developer-toolbar {
    top: 0;
    bottom: auto;
    border-top: 0;
    border-bottom: 1px solid #111;
}

.zdt-toolbar-detail {
    top: 40px;
    bottom: auto;
}

.zdt-toolbar-detail:before,
.zdt-toolbar-detail:after {
    left: 14px;
    top: -10px;
    bottom: auto;
    border-top: 0;
    border-bottom: 10px solid #68B604;
}
<?php endif; ?>
</style>
<!-- END Zend Developer Toolbar Style -->