<!-- START Zend Developer Toolbar -->
<?php if (isset($this->multitoolbar) && $this->multitoolbar): ?>
<div class="zend-developer-toolbar">
<?php else: ?>
<div id="zend-developer-toolbar" class="zend-developer-toolbar">
<?php endif; ?>
    <?php foreach ($this->entries as $entry): ?>
        <?php echo $entry; ?>
    <?php endforeach; ?>
    <a id="zdf-toolbar-toggle" class="zdf-toolbar-hide-button" href="javascript:void(0);"></a>
</div>
<!-- END Zend Developer Toolbar -->