<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img alt="Zend Framework" src="data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAB8AAAAPCAYAAAAceBSiAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH3wkFCwsuJgWt/AAAAeVJREFUOMud1E+ITmEUx/HPOx6ZIbMkK8nCwtiMaYjsdUtKIiuNotvYCCWbsaDMwsLyNqWUjSKUXMpKspgUpig1q0HjT0JNajIPY/O8dXt739d9nbqL53TO8z3Pub9zGpCXYRQ5+rCsuy1jEI9xA6sxig0INfKhgRchHTbhCPrVsxlMYj+KVEwvtoTDfemwosfkq/iOsf8Aw9cii3ebL3+Oc6kd1bYt4Ch2YWXynS+yeD0vw4nU7l5sGe9TlwUosjiL2dbIvAx7sbECvpM+eIi3NXXSwG+8w3yRxaWms63lZRjANLYl1yzGiiw+a4nbgoNJN39agBEviyxOtWOELtXex1DlfLYNeBxXMNDhjgX86ATo6/DqS+l/NjtzEo9aYkZwqAsY5nChNjwvwx4cx9rkuoUHRRZ/tYTu/ofgZnCsTV77tudlGEywdcn1E5NFFufa5N5OmpDEVBXW5yKLH+psmir8aRqrZkd2Flmc7nZBXoZhnMJwcyKKLE7UmbtQueQiRirgRVzLy7BYKbKRciaKLN7Ly3AGlyuj+AXf6g59SODNON2yXvuxtUPemrwMQzhQAcNr3KwNz8uwHm+wqodNFbED2yu+Jxgvsvipl5cH7Ou2cNpMyKskrJm03eaLLH7sdcH/BbxPiBhQm2E3AAAAAElFTkSuQmCC">
        <div class="zdt-toolbar-detail">
            <span class="zdt-toolbar-info">
                <a href="<?php echo $doc_uri ?>">Documentation</a>
            </span>
            <span class="zdt-toolbar-info zdt-toolbar-spacing">
                <a href="http://modules.zendframework.com/">Modules Gallery</a>
            </span>
            <span class="zdt-toolbar-info">
                <span class="zdt-detail-label">PHP Version</span>
                <span class="zdt-detail-value"><?php echo $this->php_version; ?></span>
            </span>
            <span class="zdt-toolbar-info">
                <span class="zdt-detail-label">Extensions</span>
                <span class="zdt-detail-value">
                    <span class="zdt-toolbar-status zdt-toolbar-status-<?php echo ($this->has_intl) ? 'green' : 'red'; ?>"
                          title="<?php echo $intlText = 'intl extension ' . ($this->has_intl ? 'enabled' : 'disabled'); ?>"
                    >intl</span>
                </span>
            </span>
            <?php if (isset($this->modules)) : ?>
                <span class="zdt-toolbar-info">
                    <?php echo $this->ZendDeveloperToolsDetailArray('Modules', $this->modules); ?>
                </span>
            <?php endif; ?>
        </div>
    </div>
</div>
